[tox]
envlist =
    lint
    py{310,311,312,313,314}-django{42,51,52}

[testenv]
passenv=ELASTICSEARCH_HOST
dependency_groups =
    tests
deps =
    django42: Django>=4.2,<5.0
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<6.0
commands=
    python3 manage.py test {posargs}

; NOTE: pre-commit runs both black and flake8
[testenv:lint]
skip_install = true
deps = pre-commit~=2.17
commands = pre-commit run --all-files
